import XCTest
@testable import Amber

/// 浏览器 Cookie 导入的解析，以及登录路上那条「风控给了验证页」的识别。
///
/// 两样都是纯函数，**一条网络请求都不打**：这条路的价值恰恰在于它不碰登录接口，
/// 测试自然也不该去碰。扫码那两条接口的连通性由 scratchpad 里的探针实测，不进 CI
/// ——那是真接口，跑一轮 CI 等于替网易云做一次压测。
final class NeteaseCookieImportTests: XCTestCase {

    // 一段形状真实、值是假的 MUSIC_U（真值是一长串十六进制，这里同形不同值）。
    private static let musicU = "00A1B2C3D4E5F60718293A4B5C6D7E8F90ABCDEF1234567890FEDCBA0987654321"

    // MARK: - header 串

    func testParsesHeaderString() throws {
        let cookie = try NeteaseCookieImport.credentialCookie(
            from: "MUSIC_U=\(Self.musicU); __csrf=abc123; NMTID=xyz")
        // 只留两项，顺序固定：MUSIC_U 在前、__csrf 在后，与扫码换来的凭证同形
        XCTAssertEqual(cookie, "MUSIC_U=\(Self.musicU); __csrf=abc123")
    }

    /// 从开发者工具整行复制会带上 `Cookie:` 前缀；有人则是一行一条粘进来。
    func testHeaderToleratesPrefixAndNewlines() throws {
        let withPrefix = try NeteaseCookieImport.credentialCookie(
            from: "Cookie: MUSIC_U=\(Self.musicU); __csrf=abc123")
        XCTAssertEqual(withPrefix, "MUSIC_U=\(Self.musicU); __csrf=abc123")

        let multiline = try NeteaseCookieImport.credentialCookie(
            from: "MUSIC_U=\(Self.musicU)\n__csrf=abc123\n")
        XCTAssertEqual(multiline, "MUSIC_U=\(Self.musicU); __csrf=abc123")
    }

    /// `__csrf` 不是必需的：没有它照样能登录，eapi 那边发空串即可。
    func testCsrfIsOptional() throws {
        XCTAssertEqual(try NeteaseCookieImport.credentialCookie(from: "MUSIC_U=\(Self.musicU)"),
                       "MUSIC_U=\(Self.musicU)")
    }

    // MARK: - Cookie Editor 的 JSON

    func testParsesCookieEditorJSON() throws {
        let json = """
        [
          {"domain":".music.163.com","name":"MUSIC_U","value":"\(Self.musicU)",
           "httpOnly":true,"secure":true,"path":"/"},
          {"domain":".music.163.com","name":"__csrf","value":"abc123","path":"/"},
          {"domain":".163.com","name":"_ntes_nuid","value":"47eabde2b621ff2848404b66e558ca99"}
        ]
        """
        XCTAssertEqual(try NeteaseCookieImport.credentialCookie(from: json),
                       "MUSIC_U=\(Self.musicU); __csrf=abc123")
    }

    // MARK: - cookies.txt（Netscape）

    /// **`#HttpOnly_` 开头的不是注释**：curl 和多数导出插件用它标 HttpOnly，
    /// 而 `MUSIC_U` 恰恰就是 HttpOnly 的——把这一行当注释跳过就等于把唯一要的那项扔了。
    func testParsesNetscapeIncludingHttpOnlyLines() throws {
        let text = [
            "# Netscape HTTP Cookie File",
            "# This file was generated by Cookie Editor",
            "#HttpOnly_.music.163.com\tTRUE\t/\tTRUE\t1893456000\tMUSIC_U\t\(Self.musicU)",
            ".music.163.com\tTRUE\t/\tFALSE\t1893456000\t__csrf\tabc123",
            ".163.com\tTRUE\t/\tFALSE\t1775732160\t_ntes_nuid\t47eabde2b621ff2848404b66e558ca99",
            "",
        ].joined(separator: "\n")
        XCTAssertEqual(try NeteaseCookieImport.credentialCookie(from: text),
                       "MUSIC_U=\(Self.musicU); __csrf=abc123")
    }

    /// 三种格式是互斥的：netscape 认「一行七个制表符字段」，另两种不可能撞上，
    /// 所以「先试严格的」这个顺序不会把 header 串误吃成 netscape。
    func testFormatsDoNotShadowEachOther() {
        XCTAssertTrue(NeteaseCookieImport.parseNetscape("MUSIC_U=x; __csrf=y").isEmpty)
        XCTAssertTrue(NeteaseCookieImport.parseJSON("MUSIC_U=x; __csrf=y").isEmpty)
        XCTAssertTrue(NeteaseCookieImport.parseNetscape("[{\"name\":\"MUSIC_U\",\"value\":\"x\"}]").isEmpty)
    }

    // MARK: - 拒绝

    func testRejectsEmptyAndUnusable() {
        XCTAssertThrowsError(try NeteaseCookieImport.credentialCookie(from: "   \n ")) { error in
            XCTAssertEqual(error as? NeteaseCookieParseError, .empty)
        }
        // 认得出格式、但没有身份那一项：这份 cookie 存下来只会得到一个「看着已登录、
        // VIP 歌全取不到流」的降级状态，所以当场拒掉。
        XCTAssertThrowsError(try NeteaseCookieImport.credentialCookie(from: "__csrf=abc; NMTID=xyz")) { error in
            XCTAssertEqual(error as? NeteaseCookieParseError, .missingMusicU)
        }
        // 空值等于没有
        XCTAssertThrowsError(try NeteaseCookieImport.credentialCookie(from: "MUSIC_U=; __csrf=abc")) { error in
            XCTAssertEqual(error as? NeteaseCookieParseError, .missingMusicU)
        }
        // 三种格式都解不出东西
        XCTAssertThrowsError(try NeteaseCookieImport.credentialCookie(from: "随便一段不是 cookie 的话")) { error in
            XCTAssertEqual(error as? NeteaseCookieParseError, .unrecognized)
        }
    }

    // MARK: - 风控挑战

    /// 样本是 `/api/w/login/cellphone` 真回过来的那一份（[实测 2026-09-09 curl(eapi 探针)]，
    /// 匿名 + 格式非法的号码 + 乱填的验证码），只把 token / sign 换成同形状的假值。
    /// 手机号那条路已经删了，但这段响应形状仍是唯一一份真样本，而扫码同样可能被风控拦下
    /// （参考实现记的是 8821），所以留着钉解析。
    /// 注意 `blockText` 末尾那个真实存在的制表符——解析时要 trim 掉，
    /// 不然界面上那行字后面会拖一段空白。
    private static let challengeBody: [String: Any] = {
        let json = """
        {"code":-462,"data":{"actionCode":null,"verifyType":40,"verifyId":2001,
        "verifyUrl":"https://st.music.163.com/encrypt-pages",
        "blockText":"验证成功后，可进行下一步操作哦~\\t",
        "verifyToken":"00.40.78013a8af94d66847a6ff334affaa69b.788503317",
        "btnText":null,"orpheusUrl":null,"frontRuleIds":null,
        "params":{"event_id":"00805749871671975946","sign":"14c0ab959b8827e1344d449cf319392b"},
        "url":"https://st.music.163.com/encrypt-pages?params=%7B%22sign%22%3A%2214c0ab959b8827e1344d449cf319392b%22%7D&verifyType=40&verifyId=2001&verifyToken=00.40.78013a8af94d66847a6ff334affaa69b.788503317",
        "urlAutoOpen":0},"message":null}
        """
        return (try? JSONSerialization.jsonObject(with: Data(json.utf8))) as? [String: Any] ?? [:]
    }()

    func testChallengeParsesRealResponse() throws {
        let challenge = try XCTUnwrap(NeteaseLoginChallenge(body: Self.challengeBody))
        XCTAssertEqual(challenge.url.host, "st.music.163.com")
        XCTAssertTrue(challenge.url.absoluteString.contains("verifyToken="))
        // trim 掉了尾巴上那个制表符
        XCTAssertEqual(challenge.blockText, "验证成功后，可进行下一步操作哦~")
        XCTAssertEqual(challenge.verifyToken, "00.40.78013a8af94d66847a6ff334affaa69b.788503317")
        XCTAssertEqual(challenge.errorDescription, "验证成功后，可进行下一步操作哦~")
    }

    /// 顶层 `redirectUrl` 那两种也要认出来。
    ///
    /// 形状取自 [用户实机 2026-09-09 日志实测]：eapi 回 10004「当前登录存在安全风险，请稍后
    /// 再试」，weapi 回 8810「您当前的网络环境存在安全风险」，两条都带 `hitType` /
    /// `loginType` / `redirectUrl`（日志只记 code / message / 键名，所以这里的 URL 是按真实
    /// 键名造的占位值）。这两条最初被当成普通业务错误，只把 message 显示出来，
    /// 服务端给的出路被扔了。
    func testChallengeParsesTopLevelRedirect() throws {
        let weapi: [String: Any] = [
            "code": 8810, "message": "您当前的网络环境存在安全风险",
            "hitType": 1, "loginType": 1, "toast": "请完成验证",
            "redirectUrl": "https://st.music.163.com/encrypt-pages?params=abc&verifyType=40",
        ]
        let a = try XCTUnwrap(NeteaseLoginChallenge(body: weapi))
        XCTAssertEqual(a.url.host, "st.music.163.com")
        XCTAssertEqual(a.blockText, "您当前的网络环境存在安全风险")
        // 这一种服务端不给 verifyToken，留空而不是编一个
        XCTAssertEqual(a.verifyToken, "")

        let eapi: [String: Any] = [
            "code": 10004, "message": "当前登录存在安全风险，请稍后再试",
            "hitType": 1, "loginType": 1,
            "redirectUrl": "https://st.music.163.com/encrypt-pages?params=def",
        ]
        XCTAssertEqual(try XCTUnwrap(NeteaseLoginChallenge(body: eapi)).blockText,
                       "当前登录存在安全风险，请稍后再试")

        // message 缺席时退到 toast，别让面板上是一片空白
        let onlyToast: [String: Any] = [
            "code": 8810, "toast": "请完成验证",
            "redirectUrl": "https://st.music.163.com/encrypt-pages?params=ghi",
        ]
        XCTAssertEqual(try XCTUnwrap(NeteaseLoginChallenge(body: onlyToast)).blockText, "请完成验证")
    }

    /// 认不出出路的一律不认——认错了会把普通的业务错误变成一颗打不开的「去完成验证」按钮。
    /// 扫码轮询那条尤其要紧：801 / 802 是常态，绝不能被当成挑战。
    func testChallengeRejectsOtherCodes() {
        XCTAssertNil(NeteaseLoginChallenge(body: ["code": 801, "message": "等待扫码"]))
        XCTAssertNil(NeteaseLoginChallenge(body: ["code": 503, "message": "验证码错误"]))
        XCTAssertNil(NeteaseLoginChallenge(body: ["code": 200]))
        // code 对但 data 里没有 url：拿不到出路就不该假装有
        XCTAssertNil(NeteaseLoginChallenge(body: ["code": -462, "data": ["blockText": "x"]]))
        XCTAssertNil(NeteaseLoginChallenge(body: ["code": -462]))
        // 有 redirectUrl 但 code 是 200：那是成功，不是挑战
        XCTAssertNil(NeteaseLoginChallenge(body: ["code": 200, "redirectUrl": "https://x/"]))
        // redirectUrl 不是个能解析的地址
        XCTAssertNil(NeteaseLoginChallenge(body: ["code": 8810, "redirectUrl": ""]))
    }

    // MARK: - 状态机

    /// 界面完全靠 `isBusy` / `statusText` 决定禁用与提示，取值错了就是按钮该灰不灰。
    func testCookieLoginStateBusyAndText() {
        XCTAssertTrue(NeteaseCookieLoginState.validating.isBusy)
        XCTAssertFalse(NeteaseCookieLoginState.idle.isBusy)
        XCTAssertFalse(NeteaseCookieLoginState.failed("Cookie 为空").isBusy)

        XCTAssertEqual(NeteaseCookieLoginState.idle.statusText, "")
        XCTAssertEqual(NeteaseCookieLoginState.validating.statusText, "正在校验 Cookie…")
        XCTAssertEqual(NeteaseCookieLoginState.failed("Cookie 为空").statusText, "Cookie 为空")
    }

    /// `qrAPI` 没注入时不该假装在登录：解析先跑，解析过了才轮到「服务未初始化」。
    /// 这条不碰网络——`loginWithCookie` 在`qrAPI == nil` 时同步就返回了。
    @MainActor
    func testCookieLoginReportsParseErrorBeforeService() {
        let store = NeteaseLoginStore()
        XCTAssertEqual(store.cookieState, .idle)

        store.loginWithCookie("__csrf=abc")
        XCTAssertEqual(store.cookieState,
                       .failed(NeteaseCookieParseError.missingMusicU.errorDescription ?? ""))

        store.loginWithCookie("MUSIC_U=\(Self.musicU)")
        XCTAssertEqual(store.cookieState, .failed("登录服务未初始化"))

        store.resetCookieLogin()
        XCTAssertEqual(store.cookieState, .idle)
    }
}
